=== arifkomurculer/FalconMFDAll/Charts/Balkan/balkan.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:od="urn:schemas-microsoft-com:officedata">
<xsd:element name="dataroot">
<xsd:complexType>
<xsd:sequence>
<xsd:element ref="AirportData" minOccurs="0" maxOccurs="unbounded"/>
</xsd:sequence>
<xsd:attribute name="generated" type="xsd:dateTime"/>
</xsd:complexType>
</xsd:element>
<xsd:element name="AirportData">
<xsd:annotation>
<xsd:appinfo>
<od:tableProperty name="Orientation" type="2" value="0"/>
<od:tableProperty name="GUID" type="9" value="4OGn/9sc40qm1mdkBGrASQ==
"/>
<od:tableProperty name="RowHeight" type="3" value="975"/>
<od:tableProperty name="OrderByOn" type="1" value="1"/>
<od:tableProperty name="NameMap" type="11" value="CswOVQAAAADg4af/2xzjSqbWZ2QEasBJAAAAAN5gH3Y90eRAAAAAAAAAAABBAGkA
cgBwAG8AcgB0AEQAYQB0AGEAAAAAAAAAGgugNaj+KUeGhy1JbJ6/bQcAAADg4af/
2xzjSqbWZ2QEasBJUABLAAAAAAAAAE3YG8jW8mhLnWA8ZGm853YHAAAA4OGn/9sc
40qm1mdkBGrASU4AYQBtAGUAAAAAAAAAM8/094loTk28Ta4uUXEn2gcAAADg4af/
2xzjSqbWZ2QEasBJSQBDAEEATwAAAAAAAAB6z9pDgAIvRqm/tV6KxDYJBwAAAODh
p//bHONKptZnZARqwElYAEMAbwBvAHIAAAAAAAAAFjdao8JY/kCYE5x7LPUyNgcA
AADg4af/2xzjSqbWZ2QEasBJWQBDAG8AbwByAAAAAAAAAH0Z4LsqzKpMpEU0VnQt
swYHAAAA4OGn/9sc40qm1mdkBGrASVQAdwByAAAAAAAAAPQBOIBsPYZFo1XZFw12
SmcHAAAA4OGn/9sc40qm1mdkBGrASVQAYwBuAEMAaAAAAAAAAABPf0JdsgnaTarh
RIZN3n3OBwAAAODhp//bHONKptZnZARqwElUAGMAbgBSAG4AZwAAAAAAAACAGyt6
QoObRIkOX1R+hFLZBwAAAODhp//bHONKptZnZARqwElJAGwAcwAAAAAAAAAA18Jr
KUBRSowMvQ6CHWK5BwAAAODhp//bHONKptZnZARqwElSAHcAeQAAAAAAAAAgkRR0
fPtcQK1PKk998tdiBwAAAODhp//bHONKptZnZARqwElFAGwAdgAAAAAAAACyiio2
aeeNS7hDzV/MieBlBwAAAODhp//bHONKptZnZARqwElHAFAAUwBDAG8AbwByAAAA
AAAAAHRDZBeciItHqvw8SKFccp4HAAAA4OGn/9sc40qm1mdkBGrASUEAYwBpAGsA
bABhAG0AYQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADAAAAAUAAAAAAAAAAAAAAAAA
AAAAAA==
"/>
<od:tableProperty name="DefaultView" type="2" value="2"/>
<od:tableProperty name="DisplayViewsOnSharePointSite" type="2" value="1"/>
<od:tableProperty name="TotalsRow" type="1" value="0"/>
<od:tableProperty name="FilterOnLoad" type="1" value="0"/>
<od:tableProperty name="OrderByOnLoad" type="1" value="1"/>
<od:tableProperty name="HideNewField" type="1" value="0"/>
<od:tableProperty name="BackTint" type="6" value="100"/>
<od:tableProperty name="BackShade" type="6" value="100"/>
<od:tableProperty name="ThemeFontIndex" type="4" value="-1"/>
<od:tableProperty name="AlternateBackThemeColorIndex" type="4" value="-1"/>
<od:tableProperty name="AlternateBackTint" type="6" value="100"/>
<od:tableProperty name="AlternateBackShade" type="6" value="100"/>
<od:tableProperty name="ReadOnlyWhenDisconnected" type="1" value="0"/>
<od:tableProperty name="DatasheetGridlinesThemeColorIndex" type="4" value="-1"/>
<od:tableProperty name="DatasheetForeThemeColorIndex" type="4" value="-1"/>
<od:tableProperty name="PublishToWeb" type="2" value="1"/>
<od:tableProperty name="OrderBy" type="12" value="[AirportData].[PK], [AirportData].[Name], [AirportData].[ICAO] DESC"/>
</xsd:appinfo>
</xsd:annotation>
<xsd:complexType>
<xsd:sequence>
<xsd:element name="PK" minOccurs="0" od:jetType="text" od:sqlSType="nvarchar">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="Required" type="1" value="0"/>
<od:fieldProperty name="GUID" type="9" value="GgugNaj+KUeGhy1JbJ6/bQ==
"/>
<od:fieldProperty name="ColumnWidth" type="3" value="-1"/>
<od:fieldProperty name="ColumnOrder" type="3" value="1"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="TextAlign" type="2" value="0"/>
<od:fieldProperty name="AggregateType" type="4" value="-1"/>
<od:fieldProperty name="CurrencyLCID" type="4" value="0"/>
<od:fieldProperty name="AllowZeroLength" type="1" value="1"/>
<od:fieldProperty name="DisplayControl" type="3" value="109"/>
<od:fieldProperty name="IMEMode" type="2" value="0"/>
<od:fieldProperty name="IMESentenceMode" type="2" value="3"/>
<od:fieldProperty name="UnicodeCompression" type="1" value="1"/>
<od:fieldProperty name="ResultType" type="2" value="0"/>
</xsd:appinfo>
</xsd:annotation>
<xsd:simpleType>
<xsd:restriction base="xsd:string">
<xsd:maxLength value="255"/>
</xsd:restriction>
</xsd:simpleType>
</xsd:element>
<xsd:element name="ICAO" minOccurs="0" od:jetType="text" od:sqlSType="nvarchar">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="Required" type="1" value="0"/>
<od:fieldProperty name="GUID" type="9" value="M8/094loTk28Ta4uUXEn2g==
"/>
<od:fieldProperty name="ColumnWidth" type="3" value="-1"/>
<od:fieldProperty name="ColumnOrder" type="3" value="0"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="TextAlign" type="2" value="0"/>
<od:fieldProperty name="AggregateType" type="4" value="-1"/>
<od:fieldProperty name="CurrencyLCID" type="4" value="0"/>
<od:fieldProperty name="AllowZeroLength" type="1" value="1"/>
<od:fieldProperty name="DisplayControl" type="3" value="109"/>
<od:fieldProperty name="IMEMode" type="2" value="0"/>
<od:fieldProperty name="IMESentenceMode" type="2" value="3"/>
<od:fieldProperty name="UnicodeCompression" type="1" value="1"/>
<od:fieldProperty name="ResultType" type="2" value="0"/>
</xsd:appinfo>
</xsd:annotation>
<xsd:simpleType>
<xsd:restriction base="xsd:string">
<xsd:maxLength value="255"/>
</xsd:restriction>
</xsd:simpleType>
</xsd:element>
<xsd:element name="Name" minOccurs="0" od:jetType="text" od:sqlSType="nvarchar">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="Required" type="1" value="0"/>
<od:fieldProperty name="GUID" type="9" value="TdgbyNbyaEudYDxkabzndg==
"/>
<od:fieldProperty name="ColumnWidth" type="3" value="4515"/>
<od:fieldProperty name="ColumnOrder" type="3" value="0"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="TextAlign" type="2" value="0"/>
<od:fieldProperty name="AggregateType" type="4" value="-1"/>
<od:fieldProperty name="CurrencyLCID" type="4" value="0"/>
<od:fieldProperty name="AllowZeroLength" type="1" value="1"/>
<od:fieldProperty name="DisplayControl" type="3" value="109"/>
<od:fieldProperty name="IMEMode" type="2" value="0"/>
<od:fieldProperty name="IMESentenceMode" type="2" value="3"/>
<od:fieldProperty name="UnicodeCompression" type="1" value="1"/>
<od:fieldProperty name="ResultType" type="2" value="0"/>
</xsd:appinfo>
</xsd:annotation>
<xsd:simpleType>
<xsd:restriction base="xsd:string">
<xsd:maxLength value="255"/>
</xsd:restriction>
</xsd:simpleType>
</xsd:element>
<xsd:element name="XCoor" minOccurs="0" od:jetType="text" od:sqlSType="nvarchar">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="Required" type="1" value="0"/>
<od:fieldProperty name="GUID" type="9" value="es/aQ4ACL0apv7VeisQ2CQ==
"/>
<od:fieldProperty name="ColumnWidth" type="3" value="2835"/>
<od:fieldProperty name="ColumnOrder" type="3" value="0"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="TextAlign" type="2" value="0"/>
<od:fieldProperty name="AggregateType" type="4" value="-1"/>
<od:fieldProperty name="CurrencyLCID" type="4" value="0"/>
<od:fieldProperty name="AllowZeroLength" type="1" value="1"/>
<od:fieldProperty name="DisplayControl" type="3" value="109"/>
<od:fieldProperty name="IMEMode" type="2" value="0"/>
<od:fieldProperty name="IMESentenceMode" type="2" value="3"/>
<od:fieldProperty name="UnicodeCompression" type="1" value="1"/>
<od:fieldProperty name="ResultType" type="2" value="0"/>
</xsd:appinfo>
</xsd:annotation>
<xsd:simpleType>
<xsd:restriction base="xsd:string">
<xsd:maxLength value="255"/>
</xsd:restriction>
</xsd:simpleType>
</xsd:element>
<xsd:element name="YCoor" minOccurs="0" od:jetType="text" od:sqlSType="nvarchar">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="Required" type="1" value="0"/>
<od:fieldProperty name="GUID" type="9" value="Fjdao8JY/kCYE5x7LPUyNg==
"/>
<od:fieldProperty name="ColumnWidth" type="3" value="-1"/>
<od:fieldProperty name="ColumnOrder" type="3" value="0"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="TextAlign" type="2" value="0"/>
<od:fieldProperty name="AggregateType" type="4" value="-1"/>
<od:fieldProperty name="CurrencyLCID" type="4" value="0"/>
<od:fieldProperty name="AllowZeroLength" type="1" value="1"/>
<od:fieldProperty name="DisplayControl" type="3" value="109"/>
<od:fieldProperty name="IMEMode" type="2" value="0"/>
<od:fieldProperty name="IMESentenceMode" type="2" value="3"/>
<od:fieldProperty name="UnicodeCompression" type="1" value="1"/>
<od:fieldProperty name="ResultType" type="2" value="0"/>
</xsd:appinfo>
</xsd:annotation>
<xsd:simpleType>
<xsd:restriction base="xsd:string">
<xsd:maxLength value="255"/>
</xsd:restriction>
</xsd:simpleType>
</xsd:element>
<xsd:element name="Twr" minOccurs="0" od:jetType="text" od:sqlSType="nvarchar">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="Required" type="1" value="0"/>
<od:fieldProperty name="GUID" type="9" value="fRnguyrMqkykRTRWdC2zBg==
"/>
<od:fieldProperty name="ColumnWidth" type="3" value="-1"/>
<od:fieldProperty name="ColumnOrder" type="3" value="0"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="TextAlign" type="2" value="0"/>
<od:fieldProperty name="AggregateType" type="4" value="-1"/>
<od:fieldProperty name="CurrencyLCID" type="4" value="0"/>
<od:fieldProperty name="AllowZeroLength" type="1" value="1"/>
<od:fieldProperty name="DisplayControl" type="3" value="109"/>
<od:fieldProperty name="IMEMode" type="2" value="0"/>
<od:fieldProperty name="IMESentenceMode" type="2" value="3"/>
<od:fieldProperty name="UnicodeCompression" type="1" value="1"/>
<od:fieldProperty name="ResultType" type="2" value="0"/>
</xsd:appinfo>
</xsd:annotation>
<xsd:simpleType>
<xsd:restriction base="xsd:string">
<xsd:maxLength value="255"/>
</xsd:restriction>
</xsd:simpleType>
</xsd:element>
<xsd:element name="TcnCh" minOccurs="0" od:jetType="text" od:sqlSType="nvarchar">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="Required" type="1" value="0"/>
<od:fieldProperty name="GUID" type="9" value="9AE4gGw9hkWjVdkXDXZKZw==
"/>
<od:fieldProperty name="ColumnWidth" type="3" value="-1"/>
<od:fieldProperty name="ColumnOrder" type="3" value="0"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="TextAlign" type="2" value="0"/>
<od:fieldProperty name="AggregateType" type="4" value="-1"/>
<od:fieldProperty name="CurrencyLCID" type="4" value="0"/>
<od:fieldProperty name="AllowZeroLength" type="1" value="1"/>
<od:fieldProperty name="DisplayControl" type="3" value="109"/>
<od:fieldProperty name="IMEMode" type="2" value="0"/>
<od:fieldProperty name="IMESentenceMode" type="2" value="3"/>
<od:fieldProperty name="UnicodeCompression" type="1" value="1"/>
<od:fieldProperty name="ResultType" type="2" value="0"/>
</xsd:appinfo>
</xsd:annotation>
<xsd:simpleType>
<xsd:restriction base="xsd:string">
<xsd:maxLength value="255"/>
</xsd:restriction>
</xsd:simpleType>
</xsd:element>
<xsd:element name="TcnRng" minOccurs="0" od:jetType="text" od:sqlSType="nvarchar">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="Required" type="1" value="0"/>
<od:fieldProperty name="GUID" type="9" value="T39CXbIJ2k2q4USGTd59zg==
"/>
<od:fieldProperty name="ColumnWidth" type="3" value="-1"/>
<od:fieldProperty name="ColumnOrder" type="3" value="0"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="TextAlign" type="2" value="0"/>
<od:fieldProperty name="AggregateType" type="4" value="-1"/>
<od:fieldProperty name="CurrencyLCID" type="4" value="0"/>
<od:fieldProperty name="AllowZeroLength" type="1" value="1"/>
<od:fieldProperty name="DisplayControl" type="3" value="109"/>
<od:fieldProperty name="IMEMode" type="2" value="0"/>
<od:fieldProperty name="IMESentenceMode" type="2" value="3"/>
<od:fieldProperty name="UnicodeCompression" type="1" value="1"/>
<od:fieldProperty name="ResultType" type="2" value="0"/>
</xsd:appinfo>
</xsd:annotation>
<xsd:simpleType>
<xsd:restriction base="xsd:string">
<xsd:maxLength value="255"/>
</xsd:restriction>
</xsd:simpleType>
</xsd:element>
<xsd:element name="Ils" minOccurs="0" od:jetType="text" od:sqlSType="nvarchar">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="Required" type="1" value="0"/>
<od:fieldProperty name="GUID" type="9" value="gBsrekKDm0SJDl9UfoRS2Q==
"/>
<od:fieldProperty name="ColumnWidth" type="3" value="-1"/>
<od:fieldProperty name="ColumnOrder" type="3" value="0"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="TextAlign" type="2" value="0"/>
<od:fieldProperty name="AggregateType" type="4" value="-1"/>
<od:fieldProperty name="CurrencyLCID" type="4" value="0"/>
<od:fieldProperty name="AllowZeroLength" type="1" value="1"/>
<od:fieldProperty name="DisplayControl" type="3" value="109"/>
<od:fieldProperty name="IMEMode" type="2" value="0"/>
<od:fieldProperty name="IMESentenceMode" type="2" value="3"/>
<od:fieldProperty name="UnicodeCompression" type="1" value="1"/>
<od:fieldProperty name="ResultType" type="2" value="0"/>
</xsd:appinfo>
</xsd:annotation>
<xsd:simpleType>
<xsd:restriction base="xsd:string">
<xsd:maxLength value="255"/>
</xsd:restriction>
</xsd:simpleType>
</xsd:element>
<xsd:element name="Rwy" minOccurs="0" od:jetType="text" od:sqlSType="nvarchar">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="Required" type="1" value="0"/>
<od:fieldProperty name="GUID" type="9" value="ANfCaylAUUqMDL0Ogh1iuQ==
"/>
<od:fieldProperty name="ColumnWidth" type="3" value="-1"/>
<od:fieldProperty name="ColumnOrder" type="3" value="0"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="TextAlign" type="2" value="0"/>
<od:fieldProperty name="AggregateType" type="4" value="-1"/>
<od:fieldProperty name="CurrencyLCID" type="4" value="0"/>
<od:fieldProperty name="AllowZeroLength" type="1" value="1"/>
<od:fieldProperty name="DisplayControl" type="3" value="109"/>
<od:fieldProperty name="IMEMode" type="2" value="0"/>
<od:fieldProperty name="IMESentenceMode" type="2" value="3"/>
<od:fieldProperty name="UnicodeCompression" type="1" value="1"/>
<od:fieldProperty name="ResultType" type="2" value="0"/>
</xsd:appinfo>
</xsd:annotation>
<xsd:simpleType>
<xsd:restriction base="xsd:string">
<xsd:maxLength value="255"/>
</xsd:restriction>
</xsd:simpleType>
</xsd:element>
<xsd:element name="Elv" minOccurs="0" od:jetType="text" od:sqlSType="nvarchar">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="Required" type="1" value="0"/>
<od:fieldProperty name="GUID" type="9" value="IJEUdHz7XECtTypPffLXYg==
"/>
<od:fieldProperty name="ColumnWidth" type="3" value="-1"/>
<od:fieldProperty name="ColumnOrder" type="3" value="0"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="TextAlign" type="2" value="0"/>
<od:fieldProperty name="AggregateType" type="4" value="-1"/>
<od:fieldProperty name="CurrencyLCID" type="4" value="0"/>
<od:fieldProperty name="AllowZeroLength" type="1" value="1"/>
<od:fieldProperty name="DisplayControl" type="3" value="109"/>
<od:fieldProperty name="IMEMode" type="2" value="0"/>
<od:fieldProperty name="IMESentenceMode" type="2" value="3"/>
<od:fieldProperty name="UnicodeCompression" type="1" value="1"/>
<od:fieldProperty name="ResultType" type="2" value="0"/>
</xsd:appinfo>
</xsd:annotation>
<xsd:simpleType>
<xsd:restriction base="xsd:string">
<xsd:maxLength value="255"/>
</xsd:restriction>
</xsd:simpleType>
</xsd:element>
<xsd:element name="GPSCoor" minOccurs="0" od:jetType="text" od:sqlSType="nvarchar">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="Required" type="1" value="0"/>
<od:fieldProperty name="GUID" type="9" value="sooqNmnnjUu4Q81fzIngZQ==
"/>
<od:fieldProperty name="ColumnWidth" type="3" value="2880"/>
<od:fieldProperty name="ColumnOrder" type="3" value="0"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="TextAlign" type="2" value="0"/>
<od:fieldProperty name="AggregateType" type="4" value="-1"/>
<od:fieldProperty name="CurrencyLCID" type="4" value="0"/>
<od:fieldProperty name="AllowZeroLength" type="1" value="1"/>
<od:fieldProperty name="DisplayControl" type="3" value="109"/>
<od:fieldProperty name="IMEMode" type="2" value="0"/>
<od:fieldProperty name="IMESentenceMode" type="2" value="3"/>
<od:fieldProperty name="UnicodeCompression" type="1" value="1"/>
<od:fieldProperty name="ResultType" type="2" value="0"/>
</xsd:appinfo>
</xsd:annotation>
<xsd:simpleType>
<xsd:restriction base="xsd:string">
<xsd:maxLength value="255"/>
</xsd:restriction>
</xsd:simpleType>
</xsd:element>
<xsd:element name="Aciklama" minOccurs="0" od:jetType="text" od:sqlSType="nvarchar">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="GUID" type="9" value="dENkF5yIi0eq/DxIoVxyng==
"/>
<od:fieldProperty name="ColumnWidth" type="3" value="2085"/>
<od:fieldProperty name="ColumnOrder" type="3" value="0"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="Required" type="1" value="0"/>
<od:fieldProperty name="AllowZeroLength" type="1" value="1"/>
<od:fieldProperty name="DisplayControl" type="3" value="109"/>
<od:fieldProperty name="IMEMode" type="2" value="0"/>
<od:fieldProperty name="IMESentenceMode" type="2" value="3"/>
<od:fieldProperty name="UnicodeCompression" type="1" value="1"/>
<od:fieldProperty name="TextAlign" type="2" value="0"/>
<od:fieldProperty name="AggregateType" type="4" value="-1"/>
<od:fieldProperty name="ResultType" type="2" value="0"/>
<od:fieldProperty name="CurrencyLCID" type="4" value="0"/>
</xsd:appinfo>
</xsd:annotation>
<xsd:simpleType>
<xsd:restriction base="xsd:string">
<xsd:maxLength value="255"/>
</xsd:restriction>
</xsd:simpleType>
</xsd:element>
</xsd:sequence>
</xsd:complexType>
</xsd:element>
</xsd:schema>

=== arifkomurculer/FalconMFDAll/Charts/Balkan/balkan.xml
<?xml version="1.0" encoding="UTF-8"?>
<dataroot xmlns:od="urn:schemas-microsoft-com:officedata" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"  xsi:noNamespaceSchemaLocation="balkan.xsd" generated="2016-09-20T22:10:47">
<AirportData>
<PK>1</PK>
<ICAO></ICAO>
<Name>Amendola (ITALY)</Name>
<XCoor>970</XCoor>
<YCoor>1045</YCoor>
<Twr>234.50 
118.2</Twr>
<TcnCh>099X</TcnCh>
<TcnRng>40</TcnRng>
<Ils></Ils>
<Rwy>11/29</Rwy>
<Elv>180</Elv>
<GPSCoor>N41°07.190&apos;
E16°46.553&apos;</GPSCoor>
</AirportData>
<AirportData>
<PK>2</PK>
<ICAO></ICAO>
<Name>Ampugnano (ITALY)</Name>
<XCoor>56</XCoor>
<YCoor>697</YCoor>
<Twr>- 
122.60</Twr>
<TcnCh>039x</TcnCh>
<TcnRng>25</TcnRng>
<Ils></Ils>
<Rwy>18/36</Rwy>
<Elv>600</Elv>
<GPSCoor>N42°42.027&apos;
E11°19.430&apos;</GPSCoor>
</AirportData>
<AirportData>
<PK>3</PK>
<ICAO></ICAO>
<Name>Asiago (ITALY)</Name>
<XCoor>104</XCoor>
<YCoor>150</YCoor>
<Twr>- 
122.65</Twr>
<TcnCh>081X</TcnCh>
<TcnRng>R327°</TcnRng>
<Ils>Dme17</Ils>
<Rwy>05/23 L/R</Rwy>
<Elv>3240</Elv>
<GPSCoor>N45°08.593&apos;
E11°39.344&apos;</GPSCoor>
</AirportData>
<AirportData>
<PK>4</PK>
<ICAO></ICAO>
<Name>Aviano (ITALY)</Name>
<XCoor>326</XCoor>
<YCoor>120</YCoor>
<Twr>284.65 
134.10</Twr>
<TcnCh>111X</TcnCh>
<TcnRng>40</TcnRng>
<Ils>109.5 (05)</Ils>
<Rwy>05/23</Rwy>
<Elv>320</Elv>
<GPSCoor>N45°16.137&apos;
E13°03.652&apos;</GPSCoor>
</AirportData>
<AirportData>
<PK>5</PK>
<ICAO></ICAO>
<Name>Banja Luka (BOSNIA HERZEGOVINA)</Name>
<XCoor>1288</XCoor>
<YCoor>345</YCoor>
<Twr>- 
133.75</Twr>
<TcnCh>095X</TcnCh>
<TcnRng>40</TcnRng>
<Ils>108.70 (16)</Ils>
<Rwy>16/34</Rwy>
<Elv>380</Elv>
<GPSCoor>N44°16.325&apos;
E19°04.262&apos;</GPSCoor>
</AirportData>
<AirportData>
<PK>6</PK>
<Name>Batajnica (SERBIA)</Name>
<XCoor>1897</XCoor>
<YCoor>347</YCoor>
<Twr>- 
118.15</Twr>
<Ils>108.90 (14L)</Ils>
<Rwy>16/34 L/R</Rwy>
<Elv>260</Elv>
<GPSCoor>N44°15.786&apos;
E22°52.927&apos;</GPSCoor>
</AirportData>
<AirportData>
<PK>7</PK>
<Name>Nicola Tesla (Beograd) (SERBIA)</Name>
<XCoor>1912</XCoor>
<YCoor>368</YCoor>
<Twr>- 
118.75</Twr>
<TcnCh>070X</TcnCh>
<TcnRng>150</TcnRng>
<Ils>110.30 (12)
109.90 (30)</Ils>
<Rwy>12/30</Rwy>
<Elv>250</Elv>
<GPSCoor>N44°10.398&apos;
E22°57.851&apos;</GPSCoor>
</AirportData>
<AirportData>
<PK>8</PK>
<Name>Kucova (ALBANIA)</Name>
<XCoor>1815</XCoor>
<YCoor>1198</YCoor>
<Twr>- 
131.00</Twr>
<TcnCh>124X</TcnCh>
<TcnRng>R168</TcnRng>
<Ils>Dme36</Ils>
<Rwy>02/20</Rwy>
<Elv>100</Elv>
<GPSCoor>N40°26.776&apos;
E21°42.567&apos;</GPSCoor>
<Aciklama>Berat</Aciklama>
</AirportData>
<AirportData>
<PK>9</PK>
<ICAO></ICAO>
<Name>Bihac (BOSNIA HERZEGOVINA)</Name>
<XCoor>977</XCoor>
<YCoor>364</YCoor>
<Twr>- 
123.35</Twr>
<Rwy>12/30</Rwy>
<Elv>1050</Elv>
<GPSCoor>N44°11.475&apos;
E17°07.113&apos;</GPSCoor>
</AirportData>
<AirportData>
<PK>10</PK>
<ICAO></ICAO>
<Name>Brezovac Airstrip (CROATIA)</Name>
<XCoor>1197</XCoor>
<YCoor>157</YCoor>
<Twr>- 
123.30</Twr>
<TcnCh>034X</TcnCh>
<TcnRng>R081</TcnRng>
<Ils>Dme43</Ils>
<Rwy>18/36</Rwy>
<Elv>290</Elv>
<GPSCoor>N45°07.245&apos;
E18°37.048&apos;</GPSCoor>
</AirportData>
<AirportData>
<PK>11</PK>
<ICAO></ICAO>
<Name>Bloska Polica Airstrip (SLOVENIA)</Name>
<XCoor>734</XCoor>
<YCoor>180</YCoor>
<Twr>- 
127.80</Twr>
<TcnCh>119X</TcnCh>
<TcnRng>R165</TcnRng>
<Ils>Dme27</Ils>
<Rwy>09/27</Rwy>
<Elv>2420</Elv>
<GPSCoor>N45°01.050&apos;
E15°39.759&apos;</GPSCoor>
</AirportData>
<AirportData>
<PK>12</PK>
<Name>Borgo Panigale (ITALY)</Name>
<XCoor>57</XCoor>
<YCoor>427</YCoor>
<Twr>- 
129.90</Twr>
<TcnCh>120X</TcnCh>
<TcnRng>50</TcnRng>
<Ils>108.90 (12)
109.75 (30)</Ils>
<Rwy>12/30</Rwy>
<Elv>100</Elv>
<GPSCoor>N43°54.232&apos;
E11°21.314&apos;</GPSCoor>
</AirportData>
<AirportData>
<PK>13</PK>
<ICAO></ICAO>
<Name>Bolzano (ITALY)</Name>
<XCoor>62</XCoor>
<YCoor>39</YCoor>
<Twr>- 
120.60</Twr>
<TcnCh>111X</TcnCh>
<TcnRng>40</TcnRng>
<Ils>109.10 (02L)</Ils>
<Rwy>02/20 L/R</Rwy>
<Elv>740</Elv>
<GPSCoor>N45°38.768&apos;
E11°23.509&apos;</GPSCoor>
</AirportData>
<AirportData>
<PK>14</PK>
<ICAO></ICAO>
<Name>Brcko Airstrip (BOSNIA HERZEGOVINA)</Name>
<XCoor>1560</XCoor>
<YCoor>340</YCoor>
<Twr>- 
129.20</Twr>
<TcnCh>026X</TcnCh>
<TcnRng>R348</TcnRng>
<Ils>Dme28</Ils>
<Rwy>09/27</Rwy>
<Elv>270</Elv>
<GPSCoor>N44°17.403&apos;
E20°47.167&apos;</GPSCoor>
</AirportData>
<AirportData>
<PK>15</PK>
<ICAO></ICAO>
<Name>Casale (ITALY)</Name>
<XCoor>1423</XCoor>
<YCoor>1223</YCoor>
<Twr>386.875 
118.10</Twr>
<TcnCh>079X</TcnCh>
<TcnRng>200</TcnRng>
<Ils>109.50 (33)</Ils>
<Rwy>01/19 15/33</Rwy>
<Elv>0</Elv>
<GPSCoor>N40°19.771&apos;
E19°23.621&apos;</GPSCoor>
</AirportData>
<AirportData>
<PK>16</PK>
<ICAO></ICAO>
<Name>Capodichino (ITALY)</Name>
<XCoor>670</XCoor>
<YCoor>1170</YCoor>
<Twr>- 
118.50</Twr>
<TcnCh>126X</TcnCh>
<TcnRng>40</TcnRng>
<Ils>109.50 (26) 
110.15 (08)</Ils>
<Rwy>08/26</Rwy>
<Elv>298</Elv>
<GPSCoor>N40°34.859&apos;
E14°58.033&apos;</GPSCoor>
</AirportData>
<AirportData>
<PK>17</PK>
<ICAO></ICAO>
<Name>Fontanarossa (SICILY - ITALY)</Name>
<XCoor>823</XCoor>
<YCoor>1868</YCoor>
<Twr>- 
118.60</Twr>
<TcnCh>107X</TcnCh>
<TcnRng>200</TcnRng>
<Ils>109.90 (08)</Ils>
<Rwy>08/26</Rwy>
<Elv>430</Elv>
<GPSCoor>N37°26.263&apos;
E15°39.259&apos;</GPSCoor>
</AirportData>
<AirportData>
<PK>18</PK>
<ICAO></ICAO>
<Name>Cerklje OB KRKI(SLOVENIA)</Name>
<XCoor>892</XCoor>
<YCoor>158</YCoor>
<Twr>- 
118.55</Twr>
<Rwy>08/26</Rwy>
<Elv>500</Elv>
<GPSCoor>N45°09.671&apos;
E16°53.441&apos;</GPSCoor>
</AirportData>
<AirportData>
<PK>19</PK>
<Name>Novo Mesto (SLOVENIA)</Name>
<XCoor>925</XCoor>
<YCoor>148</YCoor>
<Twr>- 
123.75</Twr>
<Rwy>09/27</Rwy>
<Elv>480</Elv>
<GPSCoor>N45°06.977&apos;
E16°40.567&apos;</GPSCoor>
<Aciklama>Cerklje Airstrip</Aciklama>
</AirportData>
<AirportData>
<PK>20</PK>
<ICAO></ICAO>
<Name>Cerrik (ALBANIA)</Name>
<XCoor>1901</XCoor>
<YCoor>1194</YCoor>
<Twr>- 
122.40</Twr>
<TcnCh>124X</TcnCh>
<TcnRng>R142</TcnRng>
<Ils>Dme28</Ils>
<Rwy>05/23 L/R</Rwy>
<Elv>420</Elv>
<GPSCoor>N40°40.247&apos;
E21°56.803&apos;</GPSCoor>
</AirportData>
<AirportData>
<PK>21</PK>
<ICAO></ICAO>
<Name>Cervia (ITALY)</Name>
<XCoor>271</XCoor>
<YCoor>492</YCoor>
<Twr>338.225 
124.90</Twr>
<TcnCh>083X</TcnCh>
<TcnRng>40</TcnRng>
<Ils>110.35 (12)</Ils>
<Rwy>12/30</Rwy>
<Elv>20</Elv>
<GPSCoor>N43°36.989&apos;
E12°40.851&apos;</GPSCoor>
</AirportData>
<AirportData>
<PK>22</PK>
<ICAO></ICAO>
<Name>Ciampino (ITALY)</Name>
<XCoor>328</XCoor>
<YCoor>988</YCoor>
<Twr>308.775 
120.50</Twr>
<TcnCh>045X</TcnCh>
<TcnRng>40</TcnRng>
<Ils>109.90 (16)</Ils>
<Rwy>16/34</Rwy>
<Elv>330</Elv>
<GPSCoor>N41°23.355&apos;
E12°57.432&apos;</GPSCoor>
</AirportData>
<AirportData>
<PK>23</PK>
<ICAO></ICAO>
<Name>Crotone (ITALY)</Name>
<XCoor>1245</XCoor>
<YCoor>1565</YCoor>
<Twr>- 
119.00</Twr>
<TcnCh>118X</TcnCh>
<TcnRng>150</TcnRng>
<Ils>-</Ils>
<Rwy>02/20</Rwy>
<Elv>440</Elv>
<GPSCoor>N38°47.628&apos;
E18°10.369&apos;</GPSCoor>
</AirportData>
<AirportData>
<PK>24</PK>
<ICAO></ICAO>
<Name>Danilovgrad Airstrip (MONTENEGRO)</Name>
<XCoor>1670</XCoor>
<YCoor>840</YCoor>
<Twr>- 
129.40</Twr>
<TcnCh>078X</TcnCh>
<TcnRng>R331</TcnRng>
<Ils>Dme11</Ils>
<Rwy>09/27</Rwy>
<Elv>170</Elv>
<GPSCoor>N42°02.153&apos;
E21°07.245&apos;</GPSCoor>
</AirportData>
<AirportData>
<PK>25</PK>
<Name>Clipi (CROATIA)</Name>
<XCoor>1499</XCoor>
<YCoor>836</YCoor>
<Twr>- 
118.425</Twr>
<TcnCh>101X</TcnCh>
<TcnRng>80</TcnRng>
<Ils>110.1 (30)</Ils>
<Rwy>12/30</Rwy>
<Elv>140</Elv>
<GPSCoor>N42°04.308&apos;
E20°04.069&apos;</GPSCoor>
<Aciklama>Dubrovnic</Aciklama>
</AirportData>
<AirportData>
<PK>26</PK>
<Name>Durres Airstrip (ALBANIA)</Name>
<XCoor>1738</XCoor>
<YCoor>1078</YCoor>
<Twr>231.4 
123.4</Twr>
<TcnCh>076X</TcnCh>
<TcnRng>R167°</TcnRng>
<Ils>Dme56</Ils>
<Rwy>18/36</Rwy>
<Elv>40</Elv>
<GPSCoor>N40°59.11&apos;
E21°19.95&apos;</GPSCoor>
<Aciklama>Son Nav Listte Bulunamadı</Aciklama>
</AirportData>
<AirportData>
<PK>27</PK>
<Name>Elbasan (ALBANIA)</Name>
<XCoor>1849</XCoor>
<YCoor>1147</YCoor>
<Twr>230.15 
119.15</Twr>
<TcnCh>076X</TcnCh>
<TcnRng>R150°</TcnRng>
<Ils>Dme86</Ils>
<Rwy>05/23 L/R</Rwy>
<Elv>440</Elv>
<GPSCoor>N40°40.25&apos;
E21°56.80&apos;</GPSCoor>
<Aciklama>Son Nav Listte Bulunamadı</Aciklama>
</AirportData>
<AirportData>
<PK>28</PK>
<ICAO></ICAO>
<Name>Falconara (ITALY)</Name>
<XCoor>487</XCoor>
<YCoor>623</YCoor>
<Twr>- 
119.80</Twr>
<TcnCh>035X</TcnCh>
<TcnRng>200</TcnRng>
<Ils>111.90 (20)</Ils>
<Rwy>02/20</Rwy>
<Elv>140</Elv>
<GPSCoor>N43°01.425&apos;
E13°59.475&apos;</GPSCoor>
</AirportData>
<AirportData>
<PK>29</PK>
<ICAO></ICAO>
<Name>Fiumicino (ITALY)</Name>
<XCoor>255</XCoor>
<YCoor>992</YCoor>
<Twr>- 
127.625</Twr>
<TcnCh>096X</TcnCh>
<TcnRng>150</TcnRng>
<Ils>108.10 (14L)
111.55 (32R)
109.75 (14R)
108.90 (32L)</Ils>
<Rwy>14/32 L/R</Rwy>
<Elv>0</Elv>
<GPSCoor>N41°22.277&apos;
E12°31.550&apos;</GPSCoor>
</AirportData>
<AirportData>
<PK>30</PK>
<ICAO></ICAO>
<Name>Forli (ITALY)</Name>
<XCoor>218</XCoor>
<YCoor>496</YCoor>
<Twr>- 
119.75</Twr>
<TcnCh>097X</TcnCh>
<TcnRng>40</TcnRng>
<Ils>109.75 (12)</Ils>
<Rwy>12/30</Rwy>
<Elv>100</Elv>
<GPSCoor>N43°35.373&apos;
E12°20.719&apos;</GPSCoor>
</AirportData>
<AirportData>
<PK>31</PK>
<ICAO></ICAO>
<Name>Frosinone (ITALY)</Name>
<XCoor>456</XCoor>
<YCoor>1013</YCoor>
<Twr>258.70 
119.35</Twr>
<TcnCh>103X</TcnCh>
<TcnRng>50</TcnRng>
<Ils>-</Ils>
<Rwy>16/34</Rwy>
<Elv>720</Elv>
<GPSCoor>N41°16.350&apos;
E13°43.106&apos;</GPSCoor>
</AirportData>
<AirportData>
<PK>32</PK>
<ICAO></ICAO>
<Name>Gino Lisa (ITALY)</Name>
<XCoor>926</XCoor>
<YCoor>1063</YCoor>
<Twr>- 
120.10</Twr>
<TcnCh>105X</TcnCh>
<TcnRng>40</TcnRng>
<Ils></Ils>
<Rwy>16/34</Rwy>
<Elv>250</Elv>
<GPSCoor>N41°08.879&apos;
E16°31.885&apos;</GPSCoor>
</AirportData>
<AirportData>
<PK>33</PK>
<ICAO></ICAO>
<Name>Gioia Del Colle (ITALY)</Name>
<XCoor>1216</XCoor>
<YCoor>1200</YCoor>
<Twr>275.325 
122.45</Twr>
<TcnCh>125X</TcnCh>
<TcnRng>150</TcnRng>
<Ils></Ils>
<Rwy>14/32 L/R</Rwy>
<Elv>1180</Elv>
<GPSCoor>N40°28.393&apos;
E18°09.613&apos;</GPSCoor>
</AirportData>
<AirportData>
<PK>34</PK>
<ICAO></ICAO>
